# Generated by Django 3.2 on 2023-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('anonimous', 'anonimous'), ('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='user'),
        ),
    ]
